#cloud-config
datasource:
 Ec2:
  strict_id: false
ssh_pwauth: no
package_update: true
write_files:
- path: /root/.config/rclone/rclone.conf
  content: |
    [s3]
    type = s3
    provider = Other
    access_key_id = {ENTER YOUR access_key_id}
    secret_access_key = {ENTER YOUR secret_access_key}
    hard_delete = true
    endpoint = https://storage.yandexcloud.net
packages:
  - rclone
  - pv
  - zstd
  - jq
runcmd:
  - fsfreeze --freeze /
  - dd if=/dev/vda bs=4M |pv|zstd -1 |rclone --s3-chunk-size=1G --s3-upload-concurrency 8 --s3-max-upload-parts 1000000 rcat s3:<BUCKET NAME>/$(date '+%Y%m%d%H%M%S').zst
  - fsfreeze --unfreeze /
  - sleep 60
  - MEDATADA_ADDRESS=169.254.169.254
  - GCE_SERVICE_ACCOUNT_PATH=computeMetadata/v1/instance/service-accounts/default/token
  - SA_TOKEN_URL=$MEDATADA_ADDRESS/$GCE_SERVICE_ACCOUNT_PATH
  - 'IAM_TOKEN=$(curl --connect-timeout 1 -s -H "Metadata-Flavor: Google" $SA_TOKEN_URL | jq ".access_token" -r)'
  - 'INSTANCE_ID=$(curl --connect-timeout 1 -s -H "Metadata-Flavor: Google" http://169.254.169.254/computeMetadata/v1/instance/id)'
  - 'curl -X DELETE https://compute.api.cloud.yandex.net/compute/v1/instances/$INSTANCE_ID -H "Authorization: Bearer ${IAM_TOKEN}" -H "Content-type: application/json"'